package com.assassin.greendaostudy.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.assassin.greendaostudy.entity.GreenEntity;
import com.assassin.greendaostudy.entity.Student;
import com.assassin.greendaostudy.entity.Teacher;
import com.assassin.greendaostudy.entity.User;

import com.assassin.greendaostudy.entity.GreenEntityDao;
import com.assassin.greendaostudy.entity.StudentDao;
import com.assassin.greendaostudy.entity.TeacherDao;
import com.assassin.greendaostudy.entity.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenEntityDaoConfig;
    private final DaoConfig studentDaoConfig;
    private final DaoConfig teacherDaoConfig;
    private final DaoConfig userDaoConfig;

    private final GreenEntityDao greenEntityDao;
    private final StudentDao studentDao;
    private final TeacherDao teacherDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenEntityDaoConfig = daoConfigMap.get(GreenEntityDao.class).clone();
        greenEntityDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        teacherDaoConfig = daoConfigMap.get(TeacherDao.class).clone();
        teacherDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        greenEntityDao = new GreenEntityDao(greenEntityDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);
        teacherDao = new TeacherDao(teacherDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(GreenEntity.class, greenEntityDao);
        registerDao(Student.class, studentDao);
        registerDao(Teacher.class, teacherDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        greenEntityDaoConfig.clearIdentityScope();
        studentDaoConfig.clearIdentityScope();
        teacherDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public GreenEntityDao getGreenEntityDao() {
        return greenEntityDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public TeacherDao getTeacherDao() {
        return teacherDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
